
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author erick
 */
public class map4 extends javax.swing.JFrame {
    simplificacao simpli = new simplificacao();
    
    int quantidadeBits=0;
    
    String[] a = new String[16];
    String[] b = new String[16];
    String[] c = new String[16];
    String[] d = new String[16];
    String[] s = new String[16];
    /**
     * Creates new form map2
     */
    public map4() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextB = new javax.swing.JTextField();
        jTextS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextC = new javax.swing.JTextField();
        jTextD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        _A_B_C_D = new javax.swing.JLabel();
        _A_B_CD = new javax.swing.JLabel();
        _A_BCD = new javax.swing.JLabel();
        _A_BC_D = new javax.swing.JLabel();
        _AB_C_D = new javax.swing.JLabel();
        _AB_CD = new javax.swing.JLabel();
        _ABCD = new javax.swing.JLabel();
        _ABC_D = new javax.swing.JLabel();
        AB_C_D = new javax.swing.JLabel();
        AB_CD = new javax.swing.JLabel();
        ABCD = new javax.swing.JLabel();
        ABC_D = new javax.swing.JLabel();
        A_B_C_D = new javax.swing.JLabel();
        A_B_CD = new javax.swing.JLabel();
        A_BCD = new javax.swing.JLabel();
        A_BC_D = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTrue = new javax.swing.JTable();
        jLabelBits = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonSimplificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionando"));

        jLabel1.setFont(new java.awt.Font("Aileron", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("A");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Aileron", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("B");

        jLabel3.setFont(new java.awt.Font("Aileron", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("S");

        jButtonAdd.setText("Adicionar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Aileron", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("C");

        jLabel7.setFont(new java.awt.Font("Aileron", 0, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("D");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(jTextD)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAdd)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 140, 370);

        _A_B_C_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(_A_B_C_D);
        _A_B_C_D.setBounds(740, 180, 50, 50);

        _A_B_CD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(_A_B_CD);
        _A_B_CD.setBounds(800, 180, 60, 40);

        _A_BCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(_A_BCD);
        _A_BCD.setBounds(870, 180, 60, 40);

        _A_BC_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(_A_BC_D);
        _A_BC_D.setBounds(930, 180, 70, 40);

        _AB_C_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(_AB_C_D);
        _AB_C_D.setBounds(730, 250, 70, 40);

        _AB_CD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(_AB_CD);
        _AB_CD.setBounds(800, 250, 60, 40);

        _ABCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(_ABCD);
        _ABCD.setBounds(870, 250, 60, 40);

        _ABC_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(_ABC_D);
        _ABC_D.setBounds(930, 250, 70, 40);

        AB_C_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AB_C_D);
        AB_C_D.setBounds(730, 310, 70, 50);

        AB_CD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(AB_CD);
        AB_CD.setBounds(800, 310, 60, 50);

        ABCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ABCD);
        ABCD.setBounds(870, 310, 60, 50);

        ABC_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ABC_D);
        ABC_D.setBounds(930, 310, 70, 50);

        A_B_C_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(A_B_C_D);
        A_B_C_D.setBounds(730, 370, 70, 50);

        A_B_CD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(A_B_CD);
        A_B_CD.setBounds(800, 370, 70, 50);

        A_BCD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(A_BCD);
        A_BCD.setBounds(860, 370, 70, 50);

        A_BC_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(A_BC_D);
        A_BC_D.setBounds(930, 370, 70, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela Verdade"));

        jTableTrue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "A", "B", "C", "D", "S"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTrue);

        jLabel4.setText("Quantidade de bits:");

        jButtonSimplificar.setText("Simplificar");
        jButtonSimplificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimplificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonSimplificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56)
                        .addComponent(jLabelBits, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jButtonSimplificar))))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(160, 50, 470, 470);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mapa-karnaugh-4var.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(620, 80, 470, 400);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(630, 60, 450, 450);

        jButtonMenu.setText("MENU");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMenu);
        jButtonMenu.setBounds(10, 420, 140, 25);

        setSize(new java.awt.Dimension(1128, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if(quantidadeBits<16)
        {
            Object row[] = {jTextA.getText(),jTextB.getText(),jTextC.getText(),jTextD.getText(),jTextS.getText()};
            
            a[quantidadeBits] = jTextA.getText();
            b[quantidadeBits] = jTextB.getText();
            c[quantidadeBits] = jTextC.getText();
            d[quantidadeBits] = jTextC.getText();
            s[quantidadeBits] = jTextS.getText();
            
            quantidadeBits++;
            ((DefaultTableModel)jTableTrue.getModel()).addRow(row);
            jLabelBits.setText(Integer.toString(quantidadeBits));
        }else
        {
            JOptionPane.showMessageDialog(null, "MAPA DE 4 VARIAVEIS, ACEITA NO MAXIMO 16 BITS! ESTUDE MAIS!");
        }
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSimplificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimplificarActionPerformed
        // TODO add your handling code here:
        preenchendoMapa();
       // _A_B.setText(simpli.transfereDados(a, b, s, quantidadeBits));
    }//GEN-LAST:event_jButtonSimplificarActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        // TODO add your handling code here:
        new tela().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonMenuActionPerformed

    void preenchendoMapa()
    {
        int i;
        for(i=0;i<quantidadeBits;i++)
        {
            if(a[i].equals("0") && b[i].equals("0") && c[i].equals("0") && d[i].equals("0")) //0000
            {
                _A_B_C_D.setText(s[i]);
            }else {
                if(a[i].equals("0") && b[i].equals("0") && c[i].equals("0") && d[i].equals("1")) //0001
                {
                    _A_B_CD.setText(s[i]);
                }else
                {
                    if(a[i].equals("0") && b[i].equals("0") && c[i].equals("1") && d[i].equals("1")) //0011
                    {
                        _A_BCD.setText(s[i]);
                    }else
                    {
                        if(a[i].equals("0") && b[i].equals("0") && c[i].equals("1") && d[i].equals("0")) //0010
                        {
                            _A_BC_D.setText(s[i]);
                        }else
                        {
                            if(a[i].equals("0") && b[i].equals("1") && c[i].equals("0") && d[i].equals("0")) //0100
                            {
                                _AB_C_D.setText(s[i]);
                            }else
                            {
                                if(a[i].equals("0") && b[i].equals("1") && c[i].equals("0") && d[i].equals("1")) //0101
                                {
                                    _AB_CD.setText(s[i]);
                                }else
                                {
                                    if(a[i].equals("0") && b[i].equals("1") && c[i].equals("1") && d[i].equals("1")) //0111
                                    {
                                        _ABCD.setText(s[i]);
                                    }else
                                    {
                                        if(a[i].equals("0") && b[i].equals("1") && c[i].equals("1") && d[i].equals("0")) //0110
                                        {
                                            _ABC_D.setText(s[i]);
                                        }else
                                        {
                                            if(a[i].equals("1") && b[i].equals("1") && c[i].equals("0") && d[i].equals("0")) //1100
                                            {
                                                AB_C_D.setText(s[i]);
                                            }else
                                            {
                                                if(a[i].equals("1") && b[i].equals("1") && c[i].equals("0") && d[i].equals("1")) //1101
                                                {
                                                    AB_CD.setText(s[i]);
                                                }else
                                                {
                                                    if(a[i].equals("1") && b[i].equals("1") && c[i].equals("1") && d[i].equals("1")) //1111
                                                    {
                                                        ABCD.setText(s[i]);
                                                    }else
                                                    {
                                                        if(a[i].equals("1") && b[i].equals("1") && c[i].equals("1") && d[i].equals("0")) //1110
                                                        {
                                                            ABC_D.setText(s[i]);
                                                        }else
                                                        {
                                                            if(a[i].equals("1") && b[i].equals("0") && c[i].equals("0") && d[i].equals("0")) //1000
                                                            {
                                                                A_B_C_D.setText(s[i]);
                                                            }else
                                                            {
                                                                if(a[i].equals("1") && b[i].equals("0") && c[i].equals("0") && d[i].equals("1")) //1001
                                                                {
                                                                    A_B_CD.setText(s[i]);
                                                                }else
                                                                {
                                                                    if(a[i].equals("1") && b[i].equals("0") && c[i].equals("1") && d[i].equals("1")) //1011
                                                                    {
                                                                        A_BCD.setText(s[i]);
                                                                    }else
                                                                    {
                                                                        if(a[i].equals("1") && b[i].equals("0") && c[i].equals("1") && d[i].equals("0")) //1010
                                                                        {
                                                                            A_BC_D.setText(s[i]);
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }   
        }
   }
    
    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new map3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABCD;
    private javax.swing.JLabel ABC_D;
    private javax.swing.JLabel AB_CD;
    private javax.swing.JLabel AB_C_D;
    private javax.swing.JLabel A_BCD;
    private javax.swing.JLabel A_BC_D;
    private javax.swing.JLabel A_B_CD;
    private javax.swing.JLabel A_B_C_D;
    private javax.swing.JLabel _ABCD;
    private javax.swing.JLabel _ABC_D;
    private javax.swing.JLabel _AB_CD;
    private javax.swing.JLabel _AB_C_D;
    private javax.swing.JLabel _A_BCD;
    private javax.swing.JLabel _A_BC_D;
    private javax.swing.JLabel _A_B_CD;
    private javax.swing.JLabel _A_B_C_D;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonSimplificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelBits;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTrue;
    private javax.swing.JTextField jTextA;
    private javax.swing.JTextField jTextB;
    private javax.swing.JTextField jTextC;
    private javax.swing.JTextField jTextD;
    private javax.swing.JTextField jTextS;
    // End of variables declaration//GEN-END:variables
}
